-- Produces the JSON served at /data/redemption-data.json (read-only).
-- Card names, banks and transfer RATIOS come from calculator-data.json / recommender-data.json;
-- this file adds what the redemption tool needs on top.
--
-- charts : award charts for the programmes whose charts are keyed by usable regions.
--          Aeroplan, Qantas and Velocity price by distance in regions that do not include India, so they
--          are left out until the tool supports distance input. Malaysia Enrich has no card route.
--          Turkish Miles&Smiles is left out: its region names are inconsistent ("South America" vs
--          "Southern America") and its chart is dated February 2024.
--          Only 'standard' and 'star_alliance_partner' prices are kept (promotions and upgrades are not).
--          Row: [origin_idx, destination_idx, cabin, units, basis, type, direction, label_idx]
--            label: KrisFlyer 'Saver'/'Advantage' award tier, otherwise the carrier scope; -1 when none
--            cabin e|p|b|f|r (economy, premium economy, business, first, room)
--            basis 0 exact, 1 starting_at | type 0 standard, 1 partner | direction 0 one_way, 1 round_trip, 2 per_night
-- xfer   : per card and programme, the same route the calculator uses (card-specific beats currency-level):
--          [min_units, multiple_units, processing_text, processing_max_hours, cap_units, cap_window]
-- modes  : per card, Rs per point for each cash-like way to redeem (card-specific beats currency-level,
--          latest as_of_month): { mode: [inr_per_unit, is_ceiling] }
--          This query also returns crawler pages that are not real cards (for example idfc:rupay or
--          hsbc:page-3). The shipped file keeps only cards present in calculator-data.json or
--          recommender-data.json, so apply that filter before using the output.
--
-- places : the shipped file also has charts.<programme>.places = [[name, region_idx, 'c'|'y']] (country or city), built from
--          corpus.award_region (explicit country/city members) plus region words ('Europe', 'Gulf', 'Africa', ...)
--          expanded to countries through corpus.award_region_member_alias and corpus.geo_region (UN M49).
--          A country the programme names explicitly is not re-claimed by a region word. UN names are shown in
--          everyday form (Netherlands, Vietnam, Turkey). The query used is not repeated here.
--
-- NOTE: data/redemption-data.json is NOT regenerated by scripts/refresh-calculator-data.mjs yet.
--       It was assembled from this query with the filter above; refresh it by hand until that is automated.
with prog(id) as (values ('krisflyer'), ('maharaja_club'), ('finnair_plus'), ('wyndham_rewards')),
award as (
  select a.programme_id, a.origin_region, a.destination_region,
         case a.cabin when 'economy' then 'e' when 'premium_economy' then 'p' when 'business' then 'b' when 'first' then 'f' when 'standard_room' then 'r' end as cabin,
         a.units, a.units_basis, a.direction, a.award_type,
         case when a.condition_note ilike 'One-way Saver%' then 'Saver' when a.condition_note ilike 'One-way Advantage%' then 'Advantage' else a.carrier_scope end as label,
         coalesce(a.effective_from, a.observed_at::date) as eff
  from corpus.award_price_current a join prog on prog.id = a.programme_id
  where a.award_type in ('standard', 'star_alliance_partner') and a.units is not null
),
regions as (
  select programme_id, array_agg(r order by r) as rs
  from (select programme_id, origin_region as r from award union select programme_id, destination_region from award) x
  group by 1
),
labels as (
  select programme_id, array_agg(label order by label) as ss
  from (select distinct programme_id, label from award where label is not null) x group by 1
),
charts as (
  select p.id as programme_id,
         jsonb_build_object(
           'regions', to_jsonb(r.rs),
           'labels', coalesce(to_jsonb(s.ss), '[]'::jsonb),
           'asOf', (select max(eff) from award a where a.programme_id = p.id),
           'rows', (select jsonb_agg(jsonb_build_array(
                      array_position(r.rs, a.origin_region) - 1, array_position(r.rs, a.destination_region) - 1,
                      a.cabin, a.units, case a.units_basis when 'starting_at' then 1 else 0 end,
                      case a.award_type when 'star_alliance_partner' then 1 else 0 end,
                      case a.direction when 'round_trip' then 1 when 'per_night' then 2 else 0 end,
                      coalesce(array_position(s.ss, a.label) - 1, -1))
                    order by a.cabin, a.units)
                    from award a where a.programme_id = p.id)
         ) as j
  from prog p join regions r on r.programme_id = p.id left join labels s on s.programme_id = p.id
),
xf_all as (
  select c.id as card_id, t.programme_id, t.min_units, t.multiple_units, t.processing_time_text, t.processing_max_hours,
         t.cap_units, t.cap_window, (t.card_id is not null) as spec, cc.is_primary
  from corpus.card c
  join corpus.card_currency cc on cc.card_id = c.id
  join corpus.transfer_partner t on t.state = 'published' and t.ratio_state = 'published' and t.from_units > 0 and t.to_units > 0
       and (t.card_id = c.id or (t.card_id is null and t.currency_id = cc.currency_id))
  join prog on prog.id = t.programme_id
  where c.status <> 'withdrawn'
    and c.id not in ('icici:pre-approved-credit-card', 'icici:tnc-for-governing-credit-card')
),
xf as (
  select distinct on (card_id, programme_id) * from xf_all order by card_id, programme_id, spec desc, is_primary desc
),
xf_json as (
  select card_id, jsonb_object_agg(programme_id, jsonb_build_array(min_units, multiple_units, processing_time_text, processing_max_hours, cap_units, cap_window)) as j
  from xf group by 1
),
mv as (
  select distinct on (c.id, v.mode) c.id as card_id, v.mode, v.inr_per_unit, v.value_is_ceiling
  from corpus.card c
  join corpus.card_currency cc on cc.card_id = c.id and cc.is_primary
  join corpus.valuation v on v.currency_id = cc.currency_id and (v.card_id = c.id or v.card_id is null)
  where c.status not in ('withdrawn', 'legacy')
    and v.mode in ('statement_credit', 'voucher', 'flight', 'hotel', 'merchandise', 'points_plus_pay', 'blended')
  order by c.id, v.mode, (v.card_id is null), v.as_of_month desc
),
mv_json as (
  select card_id, jsonb_object_agg(mode, jsonb_build_array(round(inr_per_unit, 4), coalesce(value_is_ceiling, false))) as j from mv group by 1
),
mv_cards as (
  select c.id, c.name, c.issuer_id, rc.label
  from corpus.card c
  join mv_json m on m.card_id = c.id
  left join corpus.card_currency cc on cc.card_id = c.id and cc.is_primary
  left join corpus.reward_currency rc on rc.id = cc.currency_id
)
select jsonb_build_object(
  'generatedAt', to_char(now() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
  'charts', (select jsonb_object_agg(programme_id, j) from charts),
  'xfer', (select jsonb_object_agg(card_id, j) from xf_json),
  'modes', (select jsonb_object_agg(card_id, j) from mv_json),
  'cards', (select jsonb_agg(jsonb_strip_nulls(jsonb_build_object('id', id, 'n', name, 'b', issuer_id, 'c', label)) order by issuer_id, name) from mv_cards)
) as redemption_data;
